# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config| 
  N = 2 # max number of worker nodes
  
  #=============#
  # Master Node #
  #=============#

  config.vm.define "m-k8s" do |cfg|
    cfg.vm.box = "ubuntu/focal64"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "m-k8s"
      vb.cpus = 2
      vb.memory = 4096
    end
    cfg.vm.host_name = "m-k8s"
    cfg.vm.network "private_network", ip: "192.168.56.10"
    cfg.ssh.insert_key = false
    cfg.vm.network "forwarded_port", guest: 22, host: 10022, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true   
    cfg.vm.provision "shell", path: "install_pkg.sh"
    cfg.vm.provision "shell", path: "k8s_setup.sh" 
    cfg.vm.provision "shell", path: "master_node.sh"
  end
  
  #==============#
  # Worker Nodes #
  #==============#

  (1..N).each do |i|
    config.vm.define "w#{i}-k8s" do |cfg|
      cfg.vm.box = "ubuntu/focal64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s"
        vb.cpus = 2
        vb.memory = 2048
      end
      cfg.vm.host_name = "w#{i}-k8s"
      cfg.vm.network "private_network", ip: "192.168.56.10#{i}"
      cfg.ssh.insert_key = false
      cfg.vm.network "forwarded_port", guest: 22, host: "#{i}0022",auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "install_pkg.sh"
      cfg.vm.provision "shell", path: "k8s_setup.sh" 
      cfg.vm.provision "shell", path: "work_nodes.sh"
    end
  end
end
