apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-demo
spec:
  selector:
  matchLabels:
    app: rollout-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: rollout-demo
    spec:
      containers:
      - name: webserver
        image: nginx:1.17
        ports:
        - containerPort: 80