# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config| 
  N = 2 # max number of worker nodes
  
  #=============#
  # Master Node #
  #=============#

  config.vm.define "m-k8s" do |ubuntu|
  config.vm.boot_timeout = 600 # 10 minutes
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "m-k8s"
      vb.cpus = 2
      vb.memory = 4096
    end
    ubuntu.vm.host_name = "m-k8s"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
    ubuntu.ssh.insert_key = false
    ubuntu.vm.network "forwarded_port", guest: 22, host: 10022, auto_correct: true, id: "ssh"
    ubuntu.vm.provision "shell", path: "install_pkg.sh"
    ubuntu.vm.provision "shell", path: "k8s_setup.sh" 
    ubuntu.vm.provision "shell", path: "master_node.sh"
  end
  
  #==============#
  # Worker Nodes #
  #==============#

  (1..N).each do |i|
    config.vm.define "w#{i}-k8s" do |ubuntu|
    config.vm.boot_timeout = 600 # 10 minutes
      ubuntu.vm.box = "ubuntu/focal64"
      ubuntu.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s"
        vb.cpus = 2
        vb.memory = 2048
      end
      ubuntu.vm.host_name = "w#{i}-k8s"
      ubuntu.vm.network "private_network", ip: "192.168.56.10#{i}"
      ubuntu.ssh.insert_key = false
      ubuntu.vm.network "forwarded_port", guest: 22, host: "#{i}0022",auto_correct: true, id: "ssh"
      config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
      ubuntu.vm.provision "shell", path: "install_pkg.sh"
      ubuntu.vm.provision "shell", path: "k8s_setup.sh" 
      ubuntu.vm.provision "shell", path: "work_nodes.sh"
    end
  end
end
